chatSite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from . import views
from django.conf.urls import url

app_name = 'main'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^landing/$', views.landing, name='landing'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

def home(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect("main:landing")
        else:
            return render(request, 'main/home.html', {'error_message': 'Invalid login'})
    else:
        if request.user.is_authenticated is True:
            return render(request, 'main/landing.html')
        elif request.GET.get('next'):
            return render(request, 'main/home.html', {'error_message': 'You must log in to see this page' })
        return render(request, 'main/home.html')

def logout_user(request):
    logout(request)
    return redirect('main:home')
    
def landing(request):
    return render(request, 'main/landing.html')
# Create your views here.

main/templates/main/base.html
<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <!--allow subtemplates to set page title-->
            <title>{% block title %}{% endblock %}</title>
            {% load staticfiles %}
            <!--set website icon-->
            <link rel="icon" type="image/png" href="#"/>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
            <meta name="viewport" content = "width=device-width, initial-scale=1.0">
            <style type="text/css">
              /*body{*/
              /*    background-color: black;*/
              /*    color: white;*/
              /*}*/
              {% block css %}{% endblock %}
            </style>
        </head>
        <body>
            <div class="container-fluid">
                <div class="row">
                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </body>
    </html>

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}Home | ChatSite{% endblock %}

{% block css %}
body{
  background-color: gray;
  color: black;
}
{% endblock %}


{% block body %}

<div class="col-sm-12">
    {% if error_message %}
        <h3 style="color:#8e2020;font-weight:bold;">{{ error_message }}</h3>
    {% endif %}
    <form role="form" action="{% url 'main:home' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" class="form-control" name="username" placeholder="Username">
            <label for="password">Password:</label>
            <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Log In</button>
    </form>
</div>
{% endblock %}

main/templates/main/landing.html
{% extends 'main/base.html' %}

{% block title %}Chat | ChatSite{% endblock %}

{% block css %}
body{
  background-color: lightblue;
  color: black;
}
{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>hello world</h1>
    <a href="{% url 'main:logout_user' %}"><h2>logout</h2></a>
</div>
{% endblock %}